http:
    port: 8081

storage:
    type: memory

user_groups:
    anonymous:
        rate_limit: 5000
        get: "type in ('group', 'question')"
        set: false
        update: false
        delete: false

    admin:
        get: true
        set:  true
        update: true
        delete: true

validation_rules:
    -
        type: regexp
        match: "type = 'page"
        keys:
            - body
            - name
        rule: "[a-zA-Z]*"
